# Generated by Django 4.2.4 on 2023-09-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
            preserve_default=False,
        ),
    ]
