# Generated by Django 4.2.6 on 2023-10-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymous_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_status',
            field=models.BooleanField(default=False),
        ),
    ]
